# Aliases
alias open='xdg-open'
alias clr="clear"
alias gw='gcc -Wall -Wextra -Werror'
alias gwf='gcc -Wall -Wextra -Werror -g -fsanitize=address'
alias norme='~/.norminette/norminette.rb'
alias norminette='~/.norminette/norminette.rb'
alias c='xclip'
alias v='xclip -o'

# Some env variables
export MAIL42=marvin@42.fr
export USER42=atemfack
