# Some env variables
#export MAIL42=marvin@42.fr
#export USER42=atemfack
export gai="git clone https://github.com/airseneo" # USE: _> $gai/cub3d.git
export gio="git clone https://github.com/iodevopens" # USE: _> $gio/<repo name>
export gio="git clone https://github.com/IODevPOC" # USE: _> $gpoc/<repo name>

# Aliases
alias open='xdg-open'
alias clr='clear'
alias gw='gcc -Wall -Wextra -Werror'
alias gwf='gcc -Wall -Wextra -Werror -g -fsanitize=address'
#alias norme='~/.norminette/norminette.rb'
#alias norminette='~/.norminette/norminette.rb'
alias c='xclip'
alias v='xclip -o'

DISTRO_PKG_MANAGEMENT_SYST=apt-cache
alias search='betterSearch'
betterSearch() {
	$DISTRO_PKG_MANAGEMENT_SYST search $1 | grep "^$1"
}
