version: '2'

services:

  e2e:
    build: ./tests/
    depends_on:
      - vote
      - result
      - worker
      - db
      - redis
    networks:
      - front-tier

  vote:
    image: ${VOTE_IMAGE}
    ports: ["80"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    image: ${RESULT_IMAGE}
    ports: ["4000"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: ${WORKER_IMAGE}
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
